# Generated by Django 3.0.7 on 2020-11-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('brand_name', models.CharField(max_length=30)),
                ('total_weight', models.CharField(max_length=30)),
                ('serving_size', models.CharField(max_length=30)),
                ('calories', models.CharField(max_length=30)),
                ('fat', models.CharField(max_length=30)),
                ('saturated_fat', models.CharField(max_length=30)),
                ('trans_fat', models.CharField(max_length=30)),
                ('cholesterol', models.CharField(max_length=30)),
                ('sodium', models.CharField(max_length=30)),
                ('carbohydrate', models.CharField(max_length=30)),
                ('fibre', models.CharField(max_length=30)),
                ('sugars', models.CharField(max_length=30)),
                ('protein', models.CharField(max_length=30)),
                ('vitamin_a', models.CharField(max_length=30)),
                ('vitamin_c', models.CharField(max_length=30)),
                ('calcium', models.CharField(max_length=30)),
                ('iron', models.CharField(max_length=30)),
                ('ingredients', models.TextField(blank=True)),
                ('allergens', models.TextField(blank=True)),
                ('logos', models.CharField(max_length=60)),
                ('ocr_text', models.TextField(blank=True)),
                ('image_front_url', models.TextField(blank=True)),
            ],
        ),
    ]
